# Generated by Django 4.2.11 on 2024-04-14 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ballwidth', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.3)])),
                ('planksize', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.4)])),
                ('Speed', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.05), django.core.validators.MaxValueValidator(0.3)])),
                ('acceleration', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.1)])),
                ('winpoint', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('gamemode', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('gameRunning', models.BooleanField(default=False)),
                ('gameLevel', models.PositiveIntegerField(default=0)),
                ('levelPos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
